[CmdletBinding()]param(
    [Parameter(Mandatory)][string]$BaseUri,
    [Parameter(Mandatory)][string]$TokenFile,
    [Parameter(Mandatory)][string]$ExpectedTarget)
$ErrorActionPreference='Stop'
$base=$BaseUri.TrimEnd('/');$uri=[uri]$base;$token=(Get-Content -LiteralPath $TokenFile -Raw).Trim();$auth=@{Authorization="Bearer $token"}
function Assert-True([bool]$Condition,[string]$Message){if(-not$Condition){throw "Phase 9C maximum batch failed: $Message"}}
function Invoke-Json([string]$Method,[string]$Path,[hashtable]$Headers,[object]$Body){$p=@{Uri=$base+$Path;Method=$Method;Headers=$Headers;TimeoutSec=30};if($null-ne$Body){$p.ContentType='application/json';$p.Body=$Body|ConvertTo-Json -Depth 80 -Compress};Invoke-RestMethod @p}
function Observe($Positions){Invoke-Json POST '/v0/observe/deep' $auth @{perspective='server_authoritative';domains=@('blocks','world');selector=@{chunkRadius=0;entityRadius=0;blocks=$Positions};includeProviderData=$false;budgets=@{maxResponseBytes=524288}}}
function BuildItems($Snapshot,$Original,$Fingerprint,[string]$Target){$items=@();foreach($block in @($Snapshot.server.blocks)){$originalBlock=@($Original.server.blocks|Where-Object -Property key -eq $block.key)[0];$destination=if($Target){$Target}else{$originalBlock.blockId};if($destination-eq$block.blockId){continue};$key="$($Snapshot.server.dimension)@$($block.key)";$ref=@($Snapshot.resourceRevisionRefs|Where-Object{$_.resourceType-eq'block'-and$_.resourceKey-eq$key})[0];$parts=$block.key-split',';$items+=@{operation='world.block.set';worldFingerprint=$Fingerprint;expectedResourceVersion=$ref;x=[int]$parts[0];y=[int]$parts[1];z=[int]$parts[2];blockId=$destination;expectedBlockId=$block.blockId}};return ,$items}
$session=Invoke-Json GET '/v0/session' $auth $null;Assert-True($session.target-eq$ExpectedTarget-and$session.inWorld)'Integrated world required'
$player=Invoke-Json GET '/v0/player' $auth $null;$baseX=[math]::Floor([double]$player.x/16.0)*16+4;$baseZ=[math]::Floor([double]$player.z/16.0)*16+4;$y=[math]::Floor($player.y)-16
$positions=@();0..63|ForEach-Object{$positions+=@{x=$baseX+($_%8);y=$y;z=$baseZ+[math]::Floor($_/8)}}
$fingerprint=Invoke-Json GET '/v0/world/fingerprint' $auth $null;$arm=Invoke-Json POST '/v0/debug/arm' $auth @{worldFingerprint=$fingerprint.worldFingerprint;namespaces=@('world');ttlMs=60000};$debug=@{Authorization="Bearer $token";'X-MCP-Debug-Arm'=$arm.debugArmId}
$baselineStart=Observe $positions;$baselineWatch=[Diagnostics.Stopwatch]::StartNew();Start-Sleep -Seconds 2;$original=Observe $positions;$baselineWatch.Stop();$baselineTicks=[long]$original.server.world.gameTime-[long]$baselineStart.server.world.gameTime;$baselineRate=if($baselineWatch.Elapsed.TotalSeconds-gt0){$baselineTicks/$baselineWatch.Elapsed.TotalSeconds}else{0};Assert-True(@($original.server.blocks|Where-Object -Property blockId -eq 'minecraft:stone').Count-eq64)'deterministic 64-stone layer required';$items=BuildItems $original $original $fingerprint.worldFingerprint 'minecraft:netherite_block';Assert-True($items.Count-eq64)'64 distinct loaded mutations required'
$connection=Get-NetTCPConnection -RemotePort $uri.Port -State Established -ErrorAction SilentlyContinue|Select-Object -First 1;if(-not$connection){$connection=Get-NetTCPConnection -LocalPort $uri.Port -State Listen|Select-Object -First 1};$process=Get-Process -Id $connection.OwningProcess;$workingSetBefore=$process.WorkingSet64
$watch=[Diagnostics.Stopwatch]::StartNew();$started=Invoke-Json POST '/v0/debug/batches' $debug @{items=$items;failurePolicy='STOP_ON_FAILURE';maxPerTickMutations=4;maxTotalDurationMs=30000};$terminal=Invoke-Json POST "/v0/operations/$($started.operationId)/wait" $auth @{timeoutMs=30000};$watch.Stop();Assert-True($terminal.state-eq'completed'-and$terminal.result.succeededItems-eq64-and$terminal.result.failedItems-eq0)'maximum batch did not complete'
$process.Refresh();$workingSetAfter=$process.WorkingSet64;$after=Observe $positions;$serverTicks=[long]$after.server.world.gameTime-[long]$original.server.world.gameTime;$batchRate=if($watch.Elapsed.TotalSeconds-gt0){$serverTicks/$watch.Elapsed.TotalSeconds}else{0};$relativeImpact=if($baselineRate-gt0){(($batchRate/$baselineRate)-1.0)*100.0}else{0};$responseBytes=[Text.Encoding]::UTF8.GetByteCount(($terminal.result|ConvertTo-Json -Depth 80 -Compress));$durations=@($terminal.result.items|ForEach-Object{[long]$_.durationMicros})
$restore=BuildItems $after $original $fingerprint.worldFingerprint '';$cleanupStart=Invoke-Json POST '/v0/debug/batches' $debug @{items=$restore;failurePolicy='CONTINUE_ON_FAILURE';maxPerTickMutations=4;maxTotalDurationMs=30000};$cleanup=Invoke-Json POST "/v0/operations/$($cleanupStart.operationId)/wait" $auth @{timeoutMs=30000};Assert-True($cleanup.result.failedItems-eq0)'maximum batch cleanup'
[pscustomobject]@{Result='PASS';Target=$ExpectedTarget;Items=64;PerTick=4;TotalDurationMs=$watch.ElapsedMilliseconds;RuntimeDurationMs=($terminal.result.completedAtMillis-$terminal.result.startedAtMillis);AverageItemMicros=[math]::Round(($durations|Measure-Object -Average).Average,2);MaximumItemMicros=($durations|Measure-Object -Maximum).Maximum;BaselineGameTimeRate=[math]::Round($baselineRate,2);BatchGameTimeRate=[math]::Round($batchRate,2);RelativeTickRateImpactPercent=[math]::Round($relativeImpact,2);ResponseBytes=$responseBytes;ProcessWorkingSetDeltaBytes=($workingSetAfter-$workingSetBefore);Cleanup='PASS'}
