org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

mod_id=minecraft_protocol_probe
mod_name=Minecraft Protocol Probe
mod_license=All Rights Reserved
mod_version=0.0.1-phase8
maven_group=io.github.recrivenvi
mod_environment=both
mod_authors=RecRivenVI
mod_description=Agent-native Minecraft Autonomous Testing Platform Runtime.
