[CmdletBinding()]param([Parameter(Mandatory)][string]$BaseUri,[Parameter(Mandatory)][string]$TokenFile,[Parameter(Mandatory)][string]$ExpectedTarget,[switch]$HasPhase9ADiagnostics)
$ErrorActionPreference='Stop';$base=$BaseUri.TrimEnd('/');$token=(Get-Content $TokenFile -Raw).Trim();$auth=@{Authorization="Bearer $token"}
function A([bool]$c,[string]$m){if(-not$c){throw "Phase 9B observation failed: $m"}}
function J($m,$p,$h,$b){$q=@{Uri=$base+$p;Method=$m;Headers=$h};if($null-ne$b){$q.ContentType='application/json';$q.Body=$b|ConvertTo-Json -Depth 50 -Compress};Invoke-RestMethod @q}
$session=J GET '/v0/session' $auth $null; A ($session.target -eq $ExpectedTarget -and $session.inWorld) 'world required'
$client=J GET '/v0/player'$auth $null;$x=[math]::Floor($client.x);$y=[math]::Floor($client.y)-1;$z=[math]::Floor($client.z)
$caps=J GET '/v0/observe/deep/capabilities'$auth $null;A($caps.formal-and$caps.schemaVersion-eq'phase9b-observation-v0')'formal caps'
$request=@{perspective='both';domains=@('player','entities','blocks','block_entities','chunks','world','menu');selector=@{chunkRadius=0;entityRadius=16;blocks=@(@{x=$x;y=$y;z=$z})};projection=@{playerFields=@('identity','transform','vitals','inventory','menu','dimension');entityFields=@('identity','transform','living','common_state')};includeSerializedBlockEntities=$false;includeProviderData=$false;allowReadEffects=$false;budgets=@{maxEntities=32;maxBlockEntities=32;maxResponseBytes=262144}}
$one=J POST '/v0/observe/deep'$auth $request
A ($one.formal -and $one.perspective -eq 'both') 'formal response'; A ($one.metadata.alignmentQuality -eq 'best_effort_not_same_tick') 'alignment'; A ($one.comparison.uuid.agreement) 'uuid compare'; A (@($one.resourceRevisionRefs).Count -gt 0) 'revisions'; A (@($one.server.blockEntities|Where-Object -Property readEffects -ne 'none').Count -eq 0) 'safe BE default'; A (@($one.server.blockEntities|Where-Object -Property serializedState).Count -eq 0) 'serialized BE must be opt-in'
A ($null -ne $one.server.menu -and $null -ne $one.server.menu.slots -and $null -ne $one.server.menu.carriedStack) 'formal menu snapshot'
$playerRef=@($one.resourceRevisionRefs|Where-Object -Property resourceType -eq 'player'|Where-Object -Property resourceKey -ne 'client')[0]; A ($playerRef.revisionSource -eq 'snapshot_change_sequence') 'revision source'
$two=J POST '/v0/observe/deep' $auth $request; $playerRef2=@($two.resourceRevisionRefs|Where-Object -Property resourceType -eq 'player'|Where-Object -Property resourceKey -ne 'client')[0]; A ([long]$playerRef2.revision -ge [long]$playerRef.revision) 'revision monotonic'
$far=J POST '/v0/observe/deep'$auth @{perspective='server_authoritative';domains=@('blocks');selector=@{chunkRadius=0;entityRadius=0;blocks=@(@{x=$x+100000;y=$y;z=$z+100000})};includeProviderData=$false}
$fb=@($far.server.blocks)[0];A((-not$fb.available)-and(-not$fb.loadRequested)-and$fb.reason-eq'NOT_LOADED')'no-load'
$serialized=J POST '/v0/observe/deep'$auth @{perspective='server_authoritative';domains=@('block_entities','chunks');selector=@{chunkRadius=0;entityRadius=0};includeSerializedBlockEntities=$true;includeProviderData=$false;budgets=@{maxBlockEntities=16;maxSerializedBytesPerBlockEntity=16384;maxTotalSerializedBlockEntityBytes=65536}}
A (@($serialized.server.blockEntities|Where-Object -Property readEffects -eq 'serialization_hooks_invoked').Count -eq @($serialized.server.blockEntities).Count) 'serialized effects'
$phase9a='NOT_APPLICABLE';if($HasPhase9ADiagnostics){$spike=J POST '/v0/diagnostics/phase9a/observe'$auth @{radiusChunks=0;entityRadius=16;selectedBlocks=@(@{x=$x;y=$y;z=$z})};A($spike.player.uuid-eq$one.server.player.uuid)'9A player parity';A(@($spike.blocks)[0].blockId-eq@($one.server.blocks)[0].blockId)'9A block parity';$phase9a='PASS'}
[pscustomobject]@{Target=$ExpectedTarget;Formal='PASS';ClientServer='PASS';Revision='PASS';SafeBlockEntity='PASS';SerializedOptIn='PASS';NoLoad='PASS';Phase9AComparison=$phase9a;Result='PASS'}
