[CmdletBinding()]param(
    [Parameter(Mandatory)][string]$BaseUri,
    [Parameter(Mandatory)][string]$TokenFile,
    [Parameter(Mandatory)][string]$ExpectedTarget)
$ErrorActionPreference='Stop'
$base=$BaseUri.TrimEnd('/');$token=(Get-Content -LiteralPath $TokenFile -Raw).Trim();$auth=@{Authorization="Bearer $token"}
function Assert-True([bool]$Condition,[string]$Message){if(-not$Condition){throw "Phase 9C world-exit failed: $Message"}}
function Invoke-Json([string]$Method,[string]$Path,[hashtable]$Headers,[object]$Body){$p=@{Uri=$base+$Path;Method=$Method;Headers=$Headers;TimeoutSec=20};if($null-ne$Body){$p.ContentType='application/json';$p.Body=$Body|ConvertTo-Json -Depth 80 -Compress};Invoke-RestMethod @p}
function ObserveBlocks($Positions){Invoke-Json POST '/v0/observe/deep' $auth @{perspective='server_authoritative';domains=@('blocks');selector=@{chunkRadius=0;entityRadius=0;blocks=$Positions};includeProviderData=$false;budgets=@{maxResponseBytes=524288}}}
function BuildItems($Snapshot,$OriginalSnapshot,$Fingerprint,[string]$Target){$items=@();foreach($block in @($Snapshot.server.blocks)){$originalBlock=@($OriginalSnapshot.server.blocks|Where-Object -Property key -eq $block.key)[0];if(-not$block.available-or$null-eq$originalBlock-or-not$originalBlock.available){continue};$destination=if($Target){$Target}else{$originalBlock.blockId};if(-not$destination-or$destination-eq$block.blockId){continue};$key="$($Snapshot.server.dimension)@$($block.key)";$ref=@($Snapshot.resourceRevisionRefs|Where-Object{$_.resourceType-eq'block'-and$_.resourceKey-eq$key})[0];if($null-eq$ref){continue};$p=$block.key-split',';$items+=@{operation='world.block.set';worldFingerprint=$Fingerprint;expectedResourceVersion=$ref;x=[int]$p[0];y=[int]$p[1];z=[int]$p[2];blockId=$destination;expectedBlockId=$block.blockId}};return ,$items}
function EnterWorld(){[void](Invoke-Json POST '/v0/control/emergency-release' $auth $null);$lease=Invoke-Json POST '/v0/control/acquire' $auth @{ttlMs=60000};$headers=@{Authorization="Bearer $token";'X-MCP-Control-Lease'=$lease.leaseId};try{$session=Invoke-Json GET '/v0/session' $auth $null;if($session.inWorld){return};[void](Invoke-Json POST '/v0/ui/action' $headers @{action='click';holdMs=100;selector=@{role='button';label='Singleplayer'}});$deadline=(Get-Date).AddSeconds(10);do{Start-Sleep -Milliseconds 250;$session=Invoke-Json GET '/v0/session' $auth $null}while($session.screenClass-notmatch'SelectWorldScreen'-and(Get-Date)-lt$deadline);for($i=0;$i-lt20;$i++){$tree=Invoke-Json GET '/v0/ui/tree' $auth $null;$play=@($tree.children|Where-Object -Property label -eq 'Play Selected World')[0];if($null-ne$play-and$play.active){break};[void](Invoke-Json POST '/v0/ui/action' $headers @{action='click';holdMs=100;source='explicit_coordinate';coordinates=@{x=200;y=75}});Start-Sleep -Milliseconds 300};[void](Invoke-Json POST '/v0/ui/action' $headers @{action='click';holdMs=100;selector=@{role='button';label='Play Selected World'}});$deadline=(Get-Date).AddSeconds(45);do{Start-Sleep -Milliseconds 250;$session=Invoke-Json GET '/v0/session' $auth $null}while(((-not$session.inWorld)-or$session.screenClass)-and(Get-Date)-lt$deadline);Assert-True($session.inWorld)'re-entry failed'}finally{try{[void](Invoke-Json POST '/v0/control/release' $headers $null)}catch{}}}
function ReturnToTitle(){[void](Invoke-Json POST '/v0/control/emergency-release' $auth $null);$lease=Invoke-Json POST '/v0/control/acquire' $auth @{ttlMs=15000};$headers=@{Authorization="Bearer $token";'X-MCP-Control-Lease'=$lease.leaseId};try{[void](Invoke-Json POST '/v0/input/key' $headers @{key=256;scanCode=1;action=1;modifiers=0});[void](Invoke-Json POST '/v0/input/key' $headers @{key=256;scanCode=1;action=0;modifiers=0});Start-Sleep -Milliseconds 300;$tree=Invoke-Json GET '/v0/ui/tree' $auth $null;$save=@($tree.children|Where-Object -Property label -eq 'Save and Quit to Title')[0];Assert-True($null-ne$save-and$save.active)'Save and Quit unavailable';try{[void](Invoke-Json POST '/v0/ui/action' $headers @{action='click';holdMs=100;selector=@{role='button';label='Save and Quit to Title'}})}catch{};$deadline=(Get-Date).AddSeconds(20);do{Start-Sleep -Milliseconds 250;$session=Invoke-Json GET '/v0/session' $auth $null}while($session.inWorld-and(Get-Date)-lt$deadline);Assert-True(-not$session.inWorld)'world did not exit'}finally{try{[void](Invoke-Json POST '/v0/control/release' $headers $null)}catch{}}}
$session=Invoke-Json GET '/v0/session' $auth $null;Assert-True($session.target-eq$ExpectedTarget-and$session.inWorld)'Integrated world required'
$player=Invoke-Json GET '/v0/player' $auth $null;$baseX=[math]::Floor([double]$player.x/16.0)*16+4;$y=[math]::Floor($player.y)-1;$baseZ=[math]::Floor([double]$player.z/16.0)*16+4
$positions=@();0..63|ForEach-Object{$positions+=@{x=$baseX+($_%8);y=$y;z=$baseZ+[math]::Floor($_/8)}}
$fingerprint=Invoke-Json GET '/v0/world/fingerprint' $auth $null;$arm=Invoke-Json POST '/v0/debug/arm' $auth @{worldFingerprint=$fingerprint.worldFingerprint;namespaces=@('world');ttlMs=60000};$debug=@{Authorization="Bearer $token";'X-MCP-Debug-Arm'=$arm.debugArmId}
$original=ObserveBlocks $positions;$items=BuildItems $original $original $fingerprint.worldFingerprint 'minecraft:copper_block'
foreach($index in 0..($items.Count-1)){if($original.server.blocks[$index].blockId-eq'minecraft:copper_block'){$items[$index].blockId='minecraft:iron_block'}}
$started=Invoke-Json POST '/v0/debug/batches' $debug @{items=$items;failurePolicy='CONTINUE_ON_FAILURE';maxPerTickMutations=1;maxTotalDurationMs=30000}
Start-Sleep -Milliseconds 100;ReturnToTitle
$terminal=Invoke-Json POST "/v0/operations/$($started.operationId)/wait" $auth @{timeoutMs=10000}
$sequenceAtExit=(Invoke-Json GET '/v0/debug/evidence' $auth $null).lastDebugMutationSequence;Start-Sleep -Seconds 3;$sequenceAfter=(Invoke-Json GET '/v0/debug/evidence' $auth $null).lastDebugMutationSequence
Assert-True($terminal.state-eq'completed'-and$terminal.result.status-eq'partial'-and$terminal.result.reason-in@('SERVER_AUTHORITATIVE_UNAVAILABLE','CAPABILITY_UNAVAILABLE'))'world exit did not stop batch'
Assert-True($sequenceAfter-eq$sequenceAtExit)'post-world-exit mutation observed'
EnterWorld
$fingerprintAfter=Invoke-Json GET '/v0/world/fingerprint' $auth $null;[void](Invoke-Json POST '/v0/debug/disarm' $auth $null);$arm=Invoke-Json POST '/v0/debug/arm' $auth @{worldFingerprint=$fingerprintAfter.worldFingerprint;namespaces=@('world');ttlMs=60000};$debug=@{Authorization="Bearer $token";'X-MCP-Debug-Arm'=$arm.debugArmId}
$current=ObserveBlocks $positions;$restore=BuildItems $current $original $fingerprintAfter.worldFingerprint '';if($restore.Count){$cleanupStart=Invoke-Json POST '/v0/debug/batches' $debug @{items=$restore;failurePolicy='CONTINUE_ON_FAILURE';maxPerTickMutations=4;maxTotalDurationMs=30000};$cleanup=Invoke-Json POST "/v0/operations/$($cleanupStart.operationId)/wait" $auth @{timeoutMs=30000};Assert-True($cleanup.result.failedItems-eq0)'world-exit cleanup'}
[pscustomobject]@{Result='PASS';Target=$ExpectedTarget;OperationId=$started.operationId;Status=$terminal.result.status;Reason=$terminal.result.reason;CompletedItems=$terminal.result.completedItems;NotStartedItems=$terminal.result.notStartedItems;PostExitMutations=0;Reentered='PASS';Cleanup='PASS'}
