[CmdletBinding()]param([Parameter(Mandatory)][string]$BaseUri,[Parameter(Mandatory)][string]$TokenFile,[Parameter(Mandatory)][string]$ExpectedTarget)
$ErrorActionPreference='Stop';$base=$BaseUri.TrimEnd('/');$token=(Get-Content $TokenFile -Raw).Trim();$auth=@{Authorization="Bearer $token"}
function Q($body){$sw=[Diagnostics.Stopwatch]::StartNew();$r=Invoke-RestMethod "$base/v0/observe/deep" -Method Post -Headers $auth -ContentType 'application/json' -Body ($body|ConvertTo-Json -Depth 30 -Compress);$sw.Stop();[pscustomobject]@{Response=$r;ElapsedMicros=$sw.ElapsedTicks*1000000/[Diagnostics.Stopwatch]::Frequency}}
$minimal=Q @{perspective='server_authoritative';domains=@('player');projection=@{playerFields=@('identity','transform')};includeProviderData=$false;budgets=@{maxResponseBytes=65536}}
$typical=Q @{perspective='server_authoritative';domains=@('player','entities','blocks','chunks','world');selector=@{chunkRadius=1;entityRadius=32};projection=@{entityFields=@('identity','transform','living')};includeProviderData=$true;providerIds=@('minecraft_protocol_probe:safe');budgets=@{maxEntities=64;maxResponseBytes=262144}}
$maximum=Q @{perspective='server_authoritative';domains=@('player','entities','blocks','block_entities','chunks','world','menu','providers');selector=@{chunkRadius=2;entityRadius=64};includeSerializedBlockEntities=$true;includeProviderData=$true;allowReadEffects=$true;providerIds=@('minecraft_protocol_probe:safe','minecraft_protocol_probe:lazy');budgets=@{maxEntities=128;maxBlockEntities=128;maxResponseBytes=524288}}
foreach($x in @($minimal,$typical,$maximum)){if($x.Response.responseBytes -gt $x.Response.maxResponseBytes){throw 'budget exceeded without rejection'};if($x.Response.server.ownerThreadCaptureMicros -gt 12000 -and $x.Response.server.completeness -ne 'partial'){throw 'hard owner budget not marked partial'}}
if($minimal.Response.responseBytes-ge$typical.Response.responseBytes){throw'projection did not reduce response'}
[pscustomobject]@{Target=$ExpectedTarget;MinimalCaptureMicros=$minimal.Response.server.ownerThreadCaptureMicros;MinimalBytes=$minimal.Response.responseBytes;TypicalCaptureMicros=$typical.Response.server.ownerThreadCaptureMicros;TypicalBytes=$typical.Response.responseBytes;TypicalEntities=@($typical.Response.server.entities).Count;TypicalChunks=@($typical.Response.server.chunks).Count;MaximumCaptureMicros=$maximum.Response.server.ownerThreadCaptureMicros;MaximumBytes=$maximum.Response.responseBytes;MaximumEntities=@($maximum.Response.server.entities).Count;MaximumChunks=@($maximum.Response.server.chunks).Count;Providers=@($maximum.Response.providers).Count;Projection='PASS';Budgets='PASS';Result='PASS'}
