plugins {
    id 'java-library'
    id 'net.neoforged.moddev.legacyforge' version '2.0.144'
}

def targetProperties = new Properties()
file('target.properties').withInputStream { targetProperties.load(it) }
targetProperties.each { key, value -> project.ext.set(key.toString(), value) }

version = mod_version
group = mod_group_id

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

legacyForge {
    version = "${minecraft_version}-${forge_version}"
    validateAccessTransformers = true

    runs {
        client {
            client()
            gameDirectory = file('../../runs/1.20.1-forge/client')
            systemProperty 'minecraft.protocol.probe.disablePauseOnLostFocus', 'true'
            if (project.hasProperty('mcpQuickPlayServer')) {
                programArguments.addAll '--quickPlayMultiplayer', project.property('mcpQuickPlayServer').toString()
            }
        }
        server {
            server()
            gameDirectory = file('../../runs/1.20.1-forge/server')
            programArgument '--nogui'
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

mixin {
    add sourceSets.main, "${mod_id}.refmap.json"
    config "${mod_id}.mixins.json"
}

dependencies {
    implementation project(':runtime-safety')
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
    implementation 'io.netty:netty-codec-http:4.1.82.Final'
    additionalRuntimeClasspath 'io.netty:netty-codec-http:4.1.82.Final'
}

jar {
    manifest.attributes([
            'MixinConfigs': "${mod_id}.mixins.json"
    ])
}

var generateModMetadata = tasks.register('generateModMetadata', ProcessResources) {
    var replaceProperties = [
            minecraft_version: minecraft_version,
            forge_version: forge_version,
            mod_id: mod_id,
            mod_name: mod_name,
            mod_license: mod_license,
            mod_version: mod_version,
            mod_authors: mod_authors,
            mod_description: mod_description
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from 'src/main/templates'
    into 'build/generated/sources/modMetadata'
}

sourceSets.main.resources.srcDir generateModMetadata
legacyForge.ideSyncTask generateModMetadata

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 17
}
